"""add_assets_and_plan_parameters

Revision ID: 51a7d87a3bda
Revises: 0002
Create Date: 2026-02-18 21:29:18.676958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51a7d87a3bda'
down_revision: Union[str, None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('asset_type', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('book_value', sa.Float(), nullable=True),
    sa.Column('liquidation_recovery_pct', sa.Float(), nullable=True),
    sa.Column('liquidation_value', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_company_id'), 'assets', ['company_id'], unique=False)
    op.create_table('plan_parameters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('total_contribution', sa.Float(), nullable=True),
    sa.Column('practitioner_fee_pct', sa.Float(), nullable=True),
    sa.Column('num_initial_payments', sa.Integer(), nullable=True),
    sa.Column('initial_payment_amount', sa.Float(), nullable=True),
    sa.Column('num_ongoing_payments', sa.Integer(), nullable=True),
    sa.Column('ongoing_payment_amount', sa.Float(), nullable=True),
    sa.Column('est_liquidator_fees', sa.Float(), nullable=True),
    sa.Column('est_legal_fees', sa.Float(), nullable=True),
    sa.Column('est_disbursements', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_parameters_company_id'), 'plan_parameters', ['company_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plan_parameters_company_id'), table_name='plan_parameters')
    op.drop_table('plan_parameters')
    op.drop_index(op.f('ix_assets_company_id'), table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###
